### ISSUE TITLE
New git flow strategy?

### ISSUE THREAD

**Issue by iwandejong** [COS301-SE-2024/Crop-Prediction-System#167]
Just curious, can we maybe look at changing the Github Actions workflow to only run for a specific branch (e.g. docs branch doesnt need any tests to be run)
This would only mean changing the branches' names, or "from now on".

```yaml
name: Run Backend Tests on PR to Dev

on:
  pull_request:
    branches:
      - 'dev'
    paths:
      - 'feature/backend/**'
```

**Comment by iwandejong** [comment]
We can also add a docs-ignore
```yaml
on:
  pull_request:
    branches:
      - 'dev'
    branches-ignore:
      - 'docs'
```
